In [19]:
import numpy as np
import pandas as pd
import warnings
warnings.filterwarnings('ignore')
from sklearn.datasets import fetch_california_housing

In [29]:
calif = fetch_california_housing()
print(calif)
# we only deal  with imput data , unsupervised learning

{'data': array([[   8.3252    ,   41.        ,    6.98412698, ...,    2.55555556,
          37.88      , -122.23      ],
       [   8.3014    ,   21.        ,    6.23813708, ...,    2.10984183,
          37.86      , -122.22      ],
       [   7.2574    ,   52.        ,    8.28813559, ...,    2.80225989,
          37.85      , -122.24      ],
       ...,
       [   1.7       ,   17.        ,    5.20554273, ...,    2.3256351 ,
          39.43      , -121.22      ],
       [   1.8672    ,   18.        ,    5.32951289, ...,    2.12320917,
          39.43      , -121.32      ],
       [   2.3886    ,   16.        ,    5.25471698, ...,    2.61698113,
          39.37      , -121.24      ]]), 'target': array([4.526, 3.585, 3.521, ..., 0.923, 0.847, 0.894]), 'frame': None, 'target_names': ['MedHouseVal'], 'feature_names': ['MedInc', 'HouseAge', 'AveRooms', 'AveBedrms', 'Population', 'AveOccup', 'Latitude', 'Longitude'], 'DESCR': '.. _california_housing_dataset:\n\nCalifornia Housing dataset\n-

# step 1

In [41]:
X = calif['data']

In [43]:
X.shape

(20640, 8)

In [45]:
# standardize
u = X.mean(axis = 0)
X_ = (X- u)
X_.shape

(20640, 8)

# step 2

In [50]:
# covariance of X is S --> X.T . X
S = np.dot(X_.T, X_)
print(S)
S.shape

[[ 7.44928083e+04 -5.87414892e+04  3.17132271e+04 -1.15284490e+03
   2.14665811e+05  7.64239253e+03 -6.68414144e+03 -1.19220569e+03]
 [-5.87414892e+04  3.26914042e+06 -9.85075210e+04 -9.57068430e+03
  -8.71434425e+07  3.55877856e+04  6.19883093e+03 -5.63082209e+04]
 [ 3.17132271e+04 -9.85075210e+04  1.26342314e+05  2.05124375e+04
  -4.17596549e+06 -2.57345350e+03  1.16039779e+04 -2.81760265e+03]
 [-1.15284490e+03 -9.57068430e+03  2.05124375e+04  4.63534397e+03
  -7.33246403e+05 -6.27926172e+02  1.45660332e+03  2.61505150e+02]
 [ 2.14665811e+05 -8.71434425e+07 -4.17596549e+06 -7.33246403e+05
   2.64689078e+10  1.69593140e+07 -5.43090134e+06  4.67221221e+06]
 [ 7.64239253e+03  3.55877856e+04 -2.57345350e+03 -6.27926172e+02
   1.69593140e+07  2.22632946e+06  1.08337499e+03  1.06329482e+03]
 [-6.68414144e+03  6.19883093e+03  1.16039779e+04  1.45660332e+03
  -5.43090134e+06  1.08337499e+03  9.41611579e+04 -8.16696318e+04]
 [-1.19220569e+03 -5.63082209e+04 -2.81760265e+03  2.61505150e+02
   

(8, 8)

# Step 3 -- getting eigen values and eigen vectors


In [53]:
lambdas , vectors = np.linalg.eig(S)

In [55]:
lambdas.shape

(8,)

In [57]:
lambdas[:2]

array([2.64692082e+10, 2.99909311e+06])

In [59]:
vectors.shape

(8, 8)

In [61]:
# 1st eigen vectors
vectors[:,0]

array([-8.11734515e-06,  3.29264421e-03,  1.57754708e-04,  2.77006684e-05,
       -9.99994324e-01, -6.40764448e-04,  2.05179008e-04, -1.76522227e-04])

In [65]:
#top 2 eigen vectors
V = vectors[: , :2]
V.shape

(8, 2)

## step 4

In [80]:
X_.shape


(20640, 8)

In [97]:
print(X_new)

[[1103.51264821    8.56663624]
 [-975.54124442   -4.67041774]
 [ 929.54990812   20.03465092]
 ...
 [ 418.43757543  -12.90825582]
 [ 684.43952537  -12.79458051]
 [  38.43624736  -12.67037806]]


In [82]:
V.shape

(8, 2)

In [99]:
X_new = np.dot(X_ , V)
X_new.shape   # we converted 13 dimensions to 2 dimensions

(20640, 2)

In [118]:
total = sum(lambdas)

In [122]:
explained_variance = np.round(lambdas/total,3)
explained_variance 

array([1., 0., 0., 0., 0., 0., 0., 0.])

In [124]:
explained_variance[:2].sum()

1.0

In [126]:
np.cumsum(explained_variance)

array([1., 1., 1., 1., 1., 1., 1., 1.])

## Skelarn

In [102]:
from sklearn.decomposition import PCA

In [104]:
pca = PCA(n_components =2)


In [106]:
pca.fit_transform(X)

array([[-1103.51264821,     8.56663624],
       [  975.54124442,    -4.67041774],
       [ -929.54990812,    20.03465092],
       ...,
       [ -418.43757543,   -12.90825582],
       [ -684.43952537,   -12.79458051],
       [  -38.43624736,   -12.67037806]])

In [114]:
pca.explained_variance_  #Lambda1 , lambda2 # how much percent varicance is explainesd by which vector

array([1.28248501e+06, 1.45311939e+02])

In [116]:
pca.explained_variance_ratio_.sum()

0.9999026078862243